/**
 * Performance Calculation Service
 * Weighted metrics system — transparent and deterministic
 */

const PERFORMANCE_WEIGHTS = {
  targetCompletion: 0.30,
  studyConsistency: 0.25,
  skillProgress: 0.20,
  quizPerformance: 0.15,
  assignmentCompletion: 0.10,
};

/**
 * Calculate overall performance score (0-100)
 * @param {Object} data - Analytics data
 * @returns {Object} Performance breakdown
 */
export function calculatePerformance(data = {}) {
  const targetList = Array.isArray(data.rawTargets)
    ? data.rawTargets
    : Array.isArray(data.targets)
    ? data.targets
    : [];

  const sessionList = Array.isArray(data.rawSessions)
    ? data.rawSessions
    : Array.isArray(data.sessions)
    ? data.sessions
    : [];

  const quizAttempts = Array.isArray(data.quizAttempts) ? data.quizAttempts : [];
  const assignmentList = Array.isArray(data.rawAssignments)
    ? data.rawAssignments
    : Array.isArray(data.assignments)
    ? data.assignments
    : [];

  const roadmap = data.roadmap || null;

  // 1. Target Completion Rate (last 30 days)
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
  const recentTargets = targetList.filter(t => t?.date && new Date(t.date) >= thirtyDaysAgo);
  const completedTargets = recentTargets.filter(t => t.status === 'completed');
  const targetScore = recentTargets.length > 0
    ? Math.min(100, Math.round((completedTargets.length / recentTargets.length) * 100))
    : (data.targets?.totalCompleted > 0 ? Math.round((data.targets.totalCompleted / (data.targets.total || 1)) * 100) : 0);

  // 2. Study Consistency (active days in last 30 days)
  const activeDates = new Set(sessionList.map(s => s.date || s.sessionDate).filter(Boolean));
  const activeCount = [...activeDates].filter(d => new Date(d) >= thirtyDaysAgo).length;
  // If user is brand new (1 day), 1 day of activity yields baseline consistency credit
  const consistencyScore = activeCount > 0 
    ? Math.min(100, Math.max(20, Math.round((activeCount / 14) * 100))) 
    : 0;

  // 3. Skill Progress (roadmap completion)
  let skillScore = 0;
  if (roadmap?.steps && roadmap.steps.length > 0) {
    const totalProgress = roadmap.steps.reduce((sum, s) => sum + (s.progress || 0), 0);
    skillScore = Math.round(totalProgress / roadmap.steps.length);
  }

  // 4. Quiz Performance (average of recent attempts)
  let quizScore = 0;
  if (quizAttempts.length > 0) {
    const recent = quizAttempts.slice(0, 5);
    quizScore = Math.round(recent.reduce((sum, q) => sum + (q.score || 0), 0) / recent.length);
  }

  // 5. Assignment Completion
  const assignmentScore = assignmentList.length > 0
    ? Math.round((assignmentList.filter(a => a.status === 'completed').length / assignmentList.length) * 100)
    : 0;

  // Weighted overall score
  const overallScore = Math.min(100, Math.max(0, Math.round(
    (targetScore || 0) * PERFORMANCE_WEIGHTS.targetCompletion +
    (consistencyScore || 0) * PERFORMANCE_WEIGHTS.studyConsistency +
    (skillScore || 0) * PERFORMANCE_WEIGHTS.skillProgress +
    (quizScore || 0) * PERFORMANCE_WEIGHTS.quizPerformance +
    (assignmentScore || 0) * PERFORMANCE_WEIGHTS.assignmentCompletion
  )));

  return {
    overall: isNaN(overallScore) ? 0 : overallScore,
    label: getPerformanceLabel(overallScore),
    components: {
      targetCompletion: { score: targetScore || 0, weight: PERFORMANCE_WEIGHTS.targetCompletion, label: 'Target Completion' },
      studyConsistency: { score: consistencyScore || 0, weight: PERFORMANCE_WEIGHTS.studyConsistency, label: 'Study Consistency' },
      skillProgress: { score: skillScore || 0, weight: PERFORMANCE_WEIGHTS.skillProgress, label: 'Skill Progress' },
      quizPerformance: { score: quizScore || 0, weight: PERFORMANCE_WEIGHTS.quizPerformance, label: 'Quiz Performance' },
      assignmentCompletion: { score: assignmentScore || 0, weight: PERFORMANCE_WEIGHTS.assignmentCompletion, label: 'Assignment Completion' },
    },
    disclaimer: 'This score is generated by PathWise AI based on your actual activity data.',
  };
}

function getPerformanceLabel(score) {
  if (score >= 85) return { text: 'Excellent', color: 'success' };
  if (score >= 70) return { text: 'Good', color: 'primary' };
  if (score >= 55) return { text: 'Fair', color: 'warning' };
  return { text: 'Building Momentum', color: 'primary' };
}

/**
 * Generate weekly AI insight text from actual data
 */
export function generateWeeklyInsight(analytics = {}) {
  const {
    targets = { todayCompleted: 0, todayTotal: 0, totalCompleted: 0 },
    streak = { currentStreak: 0, totalActiveDays: 0 },
    studyTime = { week: 0, total: 0 },
    quizAttempts = [],
  } = analytics;

  const totalActiveDays = streak.totalActiveDays || streak.currentStreak || 0;
  const weekHrs = ((studyTime.week || 0) / 3600).toFixed(1);

  if (totalActiveDays === 0 && targets.totalCompleted === 0 && quizAttempts.length === 0) {
    return 'Welcome to PathWise AI! You have initiated your student workspace. Complete your first daily target or log a study session to generate your real-time analytics trajectory.';
  }

  if (totalActiveDays === 1) {
    return `Day 1 Activity Recorded! You have completed ${targets.totalCompleted} target(s) and logged ${weekHrs} hours of focused work. Keep building daily consistency to unlock 7-day trend analysis.`;
  }

  const completionRate = targets.total > 0
    ? Math.round((targets.totalCompleted / targets.total) * 100)
    : 0;

  const recentQuizzes = quizAttempts.slice(0, 4);
  const avgQuizScore = recentQuizzes.length > 0
    ? Math.round(recentQuizzes.reduce((s, q) => s + (q.score || 0), 0) / recentQuizzes.length)
    : null;

  let insight = `You completed approximately ${completionRate}% of your overall targets. `;

  if (parseFloat(weekHrs) > 0) {
    insight += `Focused study time is recorded at ${weekHrs} hours this week. `;
  } else {
    insight += `Try logging focused practice sessions using the Study Timer. `;
  }

  if (avgQuizScore !== null) {
    if (avgQuizScore < 75) {
      insight += `Your diagnostic quiz average is ${avgQuizScore}% — review weak topics in Study Vault. `;
    } else {
      insight += `Quiz performance is solid at ${avgQuizScore}% average. `;
    }
  }

  if (streak.currentStreak >= 3) {
    insight += `Great job maintaining your ${streak.currentStreak}-day streak! 🔥`;
  } else {
    insight += `Build a consistent daily habit to keep your streak active!`;
  }

  return insight;
}
