/**
 * FutureForge Roadmap & Target Generator
 * PathWise AI — Dynamic Skill & Career Journey Engine
 * "Forge Your Skills. Build Your Future."
 */

export const CAREER_PROFILES = {
  'Software Engineer': {
    title: 'Software Engineer',
    defaultCountry: 'Germany',
    stages: [
      {
        id: 'stage-1',
        title: 'Programming Fundamentals (Python / C++)',
        description: 'Master core programming constructs, memory models, object-oriented concepts, and algorithmic thinking.',
        skills: ['Python / C++', 'Object-Oriented Programming', 'Time & Space Complexity', 'Debugging'],
        estimatedWeeks: 4,
        whyItMatters: 'Foundational syntax and algorithmic logic are required for all subsequent engineering modules and technical interviews.',
        conceptDetails: 'Data structures, control flow, functions, recursion, classes, pointers/references, and memory layout.',
        practiceTask: 'Build 5 console applications including an automated Grade Tracker and a Mini File Parser.',
        quizId: 'python-fundamentals',
        dailyTargets: [
          { day: 1, title: 'What is Programming & Language Syntax', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Variables, Memory & Data Types', duration: 45, difficulty: 'Easy' },
          { day: 3, title: 'Control Flow: Conditionals & Pattern Matching', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Loops, Iterators & List Comprehensions', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Functions, Scopes & Lambda Expressions', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'OOP Principles: Classes, Inheritance & Polymorphism', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Module 1 Review & Mini-Project Build', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-2',
        title: 'Data Structures & Core Algorithms (DSA)',
        description: 'Essential data structures from arrays and linked lists to trees, graphs, and dynamic programming.',
        skills: ['Arrays & Strings', 'Trees & Graphs', 'Dynamic Programming', 'LeetCode Problem Solving'],
        estimatedWeeks: 6,
        whyItMatters: 'DSA is the universal benchmark tested in international software engineering hiring rounds.',
        conceptDetails: 'Big-O asymptotic analysis, binary search trees, graph traversals (BFS/DFS), heaps, recursion trees, and memoization.',
        practiceTask: 'Solve 30 curated LeetCode Easy & Medium problems covering arrays, trees, and graphs.',
        quizId: 'dsa-fundamentals',
        dailyTargets: [
          { day: 1, title: 'Big-O Notation & Asymptotic Complexity Analysis', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Array Manipulations, Two-Pointers & Sliding Window', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Singly & Doubly Linked Lists Implementations', duration: 90, difficulty: 'Medium' },
          { day: 4, title: 'Stacks & Queues: Monotonic Stacks & Applications', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Binary Search Trees & Tree Traversals (Inorder/Preorder)', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Graph Representations & BFS/DFS Traversal Algorithms', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Introduction to Dynamic Programming & Memoization', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-3',
        title: 'Backend Systems & RESTful APIs',
        description: 'Designing scalable web services, API architecture, database schemas, and microservice communication.',
        skills: ['FastAPI / Node.js', 'PostgreSQL / SQL', 'REST APIs', 'Authentication & JWT'],
        estimatedWeeks: 5,
        whyItMatters: 'Industry backends power modern apps. Building real services demonstrates production readiness.',
        conceptDetails: 'HTTP protocols, relational database normalization, indexing, ORMs, middleware, and stateless authentication.',
        practiceTask: 'Develop an authenticated REST API for a collaborative workspace with PostgreSQL and automated tests.',
        quizId: 'backend-apis',
        dailyTargets: [
          { day: 1, title: 'HTTP Methods, Status Codes & Request Lifecycle', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Relational Database Schema Design & Normalization', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Complex SQL Queries, Joins, and Index Optimizations', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Building RESTful Endpoints with Input Validation', duration: 90, difficulty: 'Medium' },
          { day: 5, title: 'JWT Authentication & Role-Based Access Control', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'API Integration Testing & Error Handling Middleware', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Dockerizing the Backend Application', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-4',
        title: 'Git, DevOps & Cloud Deployment',
        description: 'Version control mastery, CI/CD pipelines, containerization with Docker, and cloud hosting.',
        skills: ['Git & GitHub', 'Docker Containers', 'CI/CD Pipelines', 'Cloud Hosting (AWS/Vercel)'],
        estimatedWeeks: 3,
        whyItMatters: 'Companies expect developers to deploy, collaborate, and manage cloud workloads smoothly.',
        conceptDetails: 'Branching strategies, merge conflict resolution, Dockerfiles, multi-stage builds, and automated GitHub Actions.',
        practiceTask: 'Set up an automated GitHub Actions pipeline that lints, tests, and deploys a live application.',
        quizId: 'devops-git',
        dailyTargets: [
          { day: 1, title: 'Advanced Git: Interactive Rebase, Cherry-Pick & Branching', duration: 45, difficulty: 'Medium' },
          { day: 2, title: 'Docker Basics: Images, Containers & Volumes', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Writing Multi-Stage Dockerfiles for Production', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Docker Compose for Multi-Service Local Environments', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Configuring GitHub Actions for Continuous Integration', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Deploying Containers to Cloud Platforms', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Infrastructure Monitoring & Health Check Setup', duration: 45, difficulty: 'Easy' },
        ],
      },
      {
        id: 'stage-5',
        title: 'Capstone Production Project',
        description: 'End-to-end full-stack software application solving a tangible real-world problem with live users.',
        skills: ['System Architecture', 'Frontend & Backend Integration', 'Unit & E2E Testing', 'Portfolio Documentation'],
        estimatedWeeks: 4,
        whyItMatters: 'A live, well-architected project is the #1 asset that gets engineering resumes shortlisted by recruiters.',
        conceptDetails: 'Clean architecture, state management, caching (Redis), responsive UI, API security, and README case studies.',
        practiceTask: 'Ship and launch a full-featured web platform with live URL, demo video, and comprehensive GitHub README.',
        quizId: 'capstone-engineering',
        dailyTargets: [
          { day: 1, title: 'Project Specification & System Architecture Diagramming', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Database Schema Migration & Core Data Models Setup', duration: 90, difficulty: 'Medium' },
          { day: 3, title: 'Implementing Business Logic & Complex Backend Features', duration: 120, difficulty: 'Hard' },
          { day: 4, title: 'Building the Interactive Responsive Frontend UI', duration: 120, difficulty: 'Hard' },
          { day: 5, title: 'Adding Security Headers, Rate Limiting & Error Logging', duration: 90, difficulty: 'Medium' },
          { day: 6, title: 'Writing Unit & End-to-End Test Suites', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Deploying Production Build & Recording Video Demo', duration: 90, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-6',
        title: 'Career & Internship Readiness (Global Pathway)',
        description: 'Technical interview practice, ATS-optimized resume building, LinkedIn presence, and country pathway requirements.',
        skills: ['Technical Interview Prep', 'System Design Basics', 'ATS Resume', 'Country Language/Visa Pathway'],
        estimatedWeeks: 3,
        whyItMatters: 'Translating engineering ability into job offers requires targeted interview readiness and country-specific preparation.',
        conceptDetails: 'Behavioral STAR methodology, mock coding rounds, portfolio presentations, and language certifications (e.g. German A1/A2 for Germany).',
        practiceTask: 'Complete 3 mock coding interviews and submit 10 personalized internship/job applications.',
        quizId: 'career-readiness',
        dailyTargets: [
          { day: 1, title: 'Drafting an ATS-Compliant Technical Resume', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Optimizing LinkedIn & GitHub Profile for Recruiters', duration: 45, difficulty: 'Easy' },
          { day: 3, title: 'System Design Fundamentals: Scalability & Load Balancing', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Behavioral Questions & STAR Method Responses', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Live Coding Interview Simulation (Timed LeetCode)', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Researching Target Country Visa & Hiring Requirements', duration: 60, difficulty: 'Easy' },
          { day: 7, title: 'Submitting Target Internship / Job Applications', duration: 90, difficulty: 'Medium' },
        ],
      },
    ],
  },
  'Data Scientist': {
    title: 'Data Scientist',
    defaultCountry: 'USA',
    stages: [
      {
        id: 'stage-1',
        title: 'Python for Data Science & Mathematics',
        description: 'Master Python, NumPy, Pandas, Linear Algebra, and Multivariate Calculus fundamentals.',
        skills: ['Python', 'NumPy & Pandas', 'Linear Algebra', 'Calculus'],
        estimatedWeeks: 4,
        whyItMatters: 'Mathematical foundations and efficient matrix manipulations are crucial for data science algorithms.',
        conceptDetails: 'Vector operations, matrix decompositions, derivatives, data manipulation, and clean vectorization.',
        practiceTask: 'Clean, reshape, and analyze a real-world dataset of 500k records using Pandas.',
        quizId: 'python-data-science',
        dailyTargets: [
          { day: 1, title: 'NumPy Arrays & Multidimensional Slicing', duration: 60, difficulty: 'Easy' },
          { day: 2, title: 'Pandas DataFrames, Indexing & Merging', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Handling Missing Values & Outlier Detection', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Matrix Inverses, Eigenvalues & Dot Products', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Statistical Aggregations & GroupBy Operations', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'Exploratory Data Analysis (EDA) on Kaggle Dataset', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Building Automated Data Cleaning Pipelines', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-2',
        title: 'Statistical Inference & Exploratory Analysis',
        description: 'Probability distributions, hypothesis testing, A/B testing frameworks, and data visualization.',
        skills: ['Statistics', 'Hypothesis Testing', 'Seaborn & Matplotlib', 'A/B Testing'],
        estimatedWeeks: 4,
        whyItMatters: 'Sound statistical conclusions prevent false findings and guide business decisions.',
        conceptDetails: 'Central Limit Theorem, p-values, confidence intervals, ANOVA, and experiment design.',
        practiceTask: 'Design and evaluate a complete A/B test simulation on user conversion data.',
        quizId: 'statistics-inference',
        dailyTargets: [
          { day: 1, title: 'Probability Distributions (Normal, Binomial, Poisson)', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Central Limit Theorem & Confidence Intervals', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Hypothesis Testing: t-tests & z-tests', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Chi-Square Tests & ANOVA Calculations', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Designing an A/B Test Framework & Power Analysis', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Interactive Visualizations with Seaborn & Plotly', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Writing Statistical Findings Reports', duration: 60, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-3',
        title: 'Machine Learning Models & Scikit-Learn',
        description: 'Supervised and unsupervised learning, regression, classification, clustering, and model validation.',
        skills: ['Scikit-Learn', 'Regression & Classification', 'Ensemble Models', 'Cross-Validation'],
        estimatedWeeks: 6,
        whyItMatters: 'Core machine learning algorithms power predictive models across modern industry domains.',
        conceptDetails: 'Decision trees, Random Forests, XGBoost, k-Means, PCA, ROC-AUC, and hyperparameter tuning.',
        practiceTask: 'Train and tune an ensemble model achieving top 15% benchmark on a Kaggle competition.',
        quizId: 'machine-learning',
        dailyTargets: [
          { day: 1, title: 'Linear & Logistic Regression Implementations', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Decision Trees & Information Gain Mathematics', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Random Forests & Gradient Boosting (XGBoost/LightGBM)', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'K-Means Clustering & Dimensionality Reduction (PCA)', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Feature Engineering & One-Hot Encoding Pipelines', duration: 90, difficulty: 'Medium' },
          { day: 6, title: 'Hyperparameter Tuning with GridSearch & Optuna', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Model Evaluation Metrics: Precision, Recall & ROC-AUC', duration: 60, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-4',
        title: 'Deep Learning & Neural Networks',
        description: 'Deep neural architectures, PyTorch, computer vision or NLP basics, and transfer learning.',
        skills: ['PyTorch', 'Neural Networks', 'Computer Vision / NLP', 'Transfer Learning'],
        estimatedWeeks: 5,
        whyItMatters: 'Modern AI relies on deep neural networks for unstructured image, text, and audio data.',
        conceptDetails: 'Backpropagation, gradient descent, CNNs, Transformers, attention mechanisms, and fine-tuning.',
        practiceTask: 'Fine-tune a pretrained model on custom dataset with PyTorch and deploy an inference API.',
        quizId: 'deep-learning',
        dailyTargets: [
          { day: 1, title: 'Perceptrons, Activation Functions & Backpropagation', duration: 90, difficulty: 'Hard' },
          { day: 2, title: 'PyTorch Tensors, Autograd & Building Custom Modules', duration: 90, difficulty: 'Medium' },
          { day: 3, title: 'Convolutional Neural Networks (CNN) for Image Tasks', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Recurrent Architectures & Transformers Basics', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Transfer Learning with HuggingFace / PyTorch Vision', duration: 90, difficulty: 'Medium' },
          { day: 6, title: 'Preventing Overfitting: Dropout, L2 & Early Stopping', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Exporting Models to ONNX for High-Speed Inference', duration: 60, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-5',
        title: 'MLOps, Data Pipelines & Model Deployment',
        description: 'Deploying machine learning models as production APIs with Docker, FastAPI, and MLflow tracking.',
        skills: ['FastAPI', 'MLflow', 'Docker for ML', 'Model Monitoring'],
        estimatedWeeks: 4,
        whyItMatters: 'Data science without production deployment remains unused prototypes. MLOps ensures business value.',
        conceptDetails: 'Model registry, artifact storage, inference latency optimization, batch vs streaming predictions, and drift detection.',
        practiceTask: 'Deploy an automated ML pipeline with model retraining triggers on AWS/GCP.',
        quizId: 'mlops-deployment',
        dailyTargets: [
          { day: 1, title: 'Wrapping ML Models in High-Performance FastAPI Endpoints', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Experiment Tracking & Model Versioning with MLflow', duration: 90, difficulty: 'Medium' },
          { day: 3, title: 'Containerizing Machine Learning Environments with Docker', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Setting Up Data Validation with Great Expectations', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Automating Training Pipelines with GitHub Actions', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Concept Drift & Data Drift Monitoring Strategies', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Deploying Live Inference Service to Cloud Infrastructure', duration: 90, difficulty: 'Hard' },
        ],
      },
    ],
  },
  'Full Stack Developer': {
    title: 'Full Stack Developer',
    defaultCountry: 'Germany',
    stages: [
      {
        id: 'stage-1',
        title: 'Modern JavaScript & Frontend Architecture',
        description: 'ES6+, TypeScript fundamentals, DOM manipulation, asynchronous programming, and responsive component UI.',
        skills: ['JavaScript / TypeScript', 'React.js', 'State Management', 'CSS & Tailwind'],
        estimatedWeeks: 4,
        whyItMatters: 'Dynamic user interfaces require clean state architecture and modern TypeScript rigor.',
        conceptDetails: 'Closures, Event Loop, Promises, React Hooks, Component Lifecycle, and Performance Profiling.',
        practiceTask: 'Build an interactive Kanban board with real-time drag-and-drop and local state synchronization.',
        quizId: 'frontend-architecture',
        dailyTargets: [
          { day: 1, title: 'Modern JavaScript: ES6+ Syntax, Destructuring & Modules', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Asynchronous JS: Event Loop, Promises & Async/Await', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'TypeScript Core: Interfaces, Types & Generics', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'React Essentials: Components, Props & Hooks (useState, useEffect)', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Advanced State: Context API & Custom Hooks', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Responsive UI Design with Modern CSS / Tailwind', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Interactive Frontend Mini-Project Build', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-2',
        title: 'Backend Engineering & RESTful APIs',
        description: 'Node.js runtime, Express/FastAPI, routing, middleware, authentication, and database connectivity.',
        skills: ['Node.js / Express', 'RESTful API Design', 'JWT Authentication', 'Input Validation'],
        estimatedWeeks: 5,
        whyItMatters: 'Full-stack engineers must engineer secure, performant server-side business logic.',
        conceptDetails: 'HTTP specification, middleware pipelines, error handling, bcrypt password hashing, and token security.',
        practiceTask: 'Create an authenticated multi-tenant API service with role-based access control.',
        quizId: 'backend-apis',
        dailyTargets: [
          { day: 1, title: 'Node.js Architecture, Event Loop & File System', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Express.js Server Setup & Routing Architecture', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Middleware Architecture: Logging, CORS & Error Handling', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Input Validation & Sanitization with Zod / Joi', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'JWT Authentication & Refresh Token Rotation', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Connecting Express to Relational & Document Databases', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Automated API Integration Tests with Supertest', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-3',
        title: 'Database Systems & Data Modeling',
        description: 'PostgreSQL, normalization, indexing, transactions, Prisma ORM, and Redis caching.',
        skills: ['PostgreSQL / SQL', 'Prisma / ORMs', 'Redis Caching', 'Data Modeling'],
        estimatedWeeks: 4,
        whyItMatters: 'Scalable web platforms depend on optimized database schemas and query execution plans.',
        conceptDetails: 'ACID compliance, foreign keys, query planning (EXPLAIN ANALYZE), caching strategies, and migrations.',
        practiceTask: 'Model an e-commerce data architecture and optimize queries using indexing and Redis caching.',
        quizId: 'database-systems',
        dailyTargets: [
          { day: 1, title: 'Relational Modeling: 3NF Normalization & Foreign Keys', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Advanced SQL: Aggregations, Joins & Subqueries', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Database Indexing Strategies & Query Optimization', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Prisma ORM: Schema Definition, Migrations & Relations', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'ACID Transactions & Database Concurrency', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Redis In-Memory Caching Implementation', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Database Performance Benchmarking Test', duration: 60, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-4',
        title: 'Full-Stack Integration, DevOps & Cloud Deployment',
        description: 'Next.js full-stack paradigms, Docker containerization, CI/CD with GitHub Actions, and cloud deployment.',
        skills: ['Next.js / SSR', 'Docker', 'CI/CD Pipelines', 'Cloud Hosting (AWS/Vercel)'],
        estimatedWeeks: 4,
        whyItMatters: 'Modern software companies demand engineers who bridge the gap from local code to live production cloud.',
        conceptDetails: 'Server-side rendering, API routes, multi-stage Docker builds, automated testing pipelines, and environment secrets.',
        practiceTask: 'Ship a full-stack SaaS platform deployed to cloud with automated CI/CD checks.',
        quizId: 'fullstack-devops',
        dailyTargets: [
          { day: 1, title: 'Next.js App Router, Server Components & Client Components', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Server Actions & Full-Stack Data Mutation', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Containerizing Full-Stack App with Docker Compose', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Writing GitHub Actions Workflows for Testing & Linting', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Production Cloud Deployment (Vercel / AWS ECS)', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'SSL Certificates, Domain Setup & Security Headers', duration: 45, difficulty: 'Easy' },
          { day: 7, title: 'End-to-End System Integration Verification', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-5',
        title: 'Capstone Production Project & System Design',
        description: 'Complete scalable application with real authentication, payments/webhooks, automated testing, and portfolio case study.',
        skills: ['System Design', 'Production Testing', 'Clean Architecture', 'Portfolio Case Study'],
        estimatedWeeks: 4,
        whyItMatters: 'A production full-stack project is the highest ROI credential for engineering recruiter shortlists.',
        conceptDetails: 'Scalability patterns, rate limiting, logging/monitoring, comprehensive README documentation, and demo videos.',
        practiceTask: 'Build, deploy, and document a production-ready web application with 100% test coverage for core paths.',
        quizId: 'capstone-fullstack',
        dailyTargets: [
          { day: 1, title: 'System Design & High-Level Architecture Diagramming', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Core Data Schema & API Contract Specification', duration: 90, difficulty: 'Medium' },
          { day: 3, title: 'Complex Business Logic & Third-Party API Integration', duration: 120, difficulty: 'Hard' },
          { day: 4, title: 'State-of-the-Art Frontend Polish & Micro-Interactions', duration: 90, difficulty: 'Medium' },
          { day: 5, title: 'Automated E2E Testing with Playwright / Cypress', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Performance Optimization & Lighthouse Audit (95+ score)', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Publishing Case Study, GitHub Documentation & Live URL', duration: 90, difficulty: 'Medium' },
        ],
      },
    ],
  },
  'AI / Machine Learning Engineer': {
    title: 'AI / Machine Learning Engineer',
    defaultCountry: 'USA',
    stages: [
      {
        id: 'stage-1',
        title: 'Mathematics, Scientific Python & Data Preprocessing',
        description: 'Linear algebra, calculus, probability distributions, NumPy, Pandas, and feature engineering pipelines.',
        skills: ['Python', 'NumPy & Pandas', 'Linear Algebra & Calculus', 'Feature Engineering'],
        estimatedWeeks: 4,
        whyItMatters: 'Algorithmic intuition in AI requires concrete understanding of vector spaces, matrix calculus, and clean data.',
        conceptDetails: 'Eigenvalues, gradients, multivariate probability, vectorization, missing value imputation, and scaling.',
        practiceTask: 'Build a reusable data preprocessing pipeline with automated statistical validation.',
        quizId: 'math-python-ai',
        dailyTargets: [
          { day: 1, title: 'Vector & Matrix Operations with NumPy', duration: 60, difficulty: 'Easy' },
          { day: 2, title: 'Multivariate Calculus: Partial Derivatives & Gradients', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Probability Distributions & Bayes Theorem Applications', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Pandas Data Wrangling & Feature Imputation', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Feature Scaling, Normalization & Encoding Techniques', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'Exploratory Data Analysis & Anomaly Detection', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'End-to-End Scientific Data Pipeline Construction', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-2',
        title: 'Classical Machine Learning & Model Evaluation',
        description: 'Supervised, unsupervised, ensemble algorithms, loss functions, hyperparameter optimization, and cross-validation.',
        skills: ['Scikit-Learn', 'Regression & Classification', 'Ensemble (XGBoost)', 'Model Metrics'],
        estimatedWeeks: 5,
        whyItMatters: 'Classical machine learning models remain the standard baseline in 80% of enterprise production systems.',
        conceptDetails: 'Bias-variance tradeoff, gradient boosting mathematics, ROC-AUC, precision-recall curves, and Optuna tuning.',
        practiceTask: 'Train and validate an ensemble classifier on an imbalanced dataset with cross-validation.',
        quizId: 'classical-ml',
        dailyTargets: [
          { day: 1, title: 'Linear & Logistic Models: Cost Functions & Optimization', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Decision Trees, Random Forests & Bagging Mechanisms', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Gradient Boosted Trees with XGBoost & LightGBM', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Unsupervised Learning: K-Means & PCA Dimensionality Reduction', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Model Evaluation: ROC-AUC, PR Curves & Confusion Matrices', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'Bayesian Hyperparameter Optimization with Optuna', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Kaggle Benchmark Challenge Submission', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-3',
        title: 'Deep Learning & Neural Architectures with PyTorch',
        description: 'Tensors, autograd, backpropagation, CNNs, RNNs, and attention mechanisms.',
        skills: ['PyTorch', 'Deep Neural Networks', 'Backpropagation', 'CNNs & Vision'],
        estimatedWeeks: 6,
        whyItMatters: 'Modern AI breakthroughs in computer vision and natural language processing rely on deep neural networks.',
        conceptDetails: 'Computational graphs, activation functions, optimizers (AdamW), regularization, and GPU acceleration.',
        practiceTask: 'Build and train a custom convolutional neural network from scratch using PyTorch.',
        quizId: 'deep-learning-pytorch',
        dailyTargets: [
          { day: 1, title: 'PyTorch Tensors, CUDA Acceleration & Autograd', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Building Multi-Layer Perceptrons & Custom nn.Module', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Backpropagation & Loss Function Implementation', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Convolutional Layers, Pooling & Image Classification', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Transfer Learning with Pretrained Models (ResNet/ViT)', duration: 90, difficulty: 'Medium' },
          { day: 6, title: 'Preventing Overfitting: Dropout, Weight Decay & Early Stopping', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Exporting PyTorch Models to TorchScript & ONNX', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-4',
        title: 'Generative AI, Large Language Models & RAG',
        description: 'Transformer architecture, self-attention, Hugging Face ecosystem, prompt engineering, and Retrieval-Augmented Generation.',
        skills: ['Transformers', 'Hugging Face', 'Vector Databases', 'RAG Architectures', 'LLM Fine-Tuning'],
        estimatedWeeks: 5,
        whyItMatters: 'Generative AI and LLM integration are the fastest growing engineering requirements in tech.',
        conceptDetails: 'Multi-head attention, positional encodings, embeddings, vector indexing (FAISS/Pinecone), and chunking strategies.',
        practiceTask: 'Build a production Retrieval-Augmented Generation (RAG) assistant with hybrid search and grounding.',
        quizId: 'genai-rag',
        dailyTargets: [
          { day: 1, title: 'Transformer Architecture: Self-Attention & Multi-Head Attention', duration: 90, difficulty: 'Hard' },
          { day: 2, title: 'Hugging Face Transformers: Tokenization & Pipeline API', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Text Embeddings & Vector Similarity Metrics', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Setting Up Vector Databases (ChromaDB / Pinecone)', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Building an End-to-End RAG Knowledge Retrieval System', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Evaluating Hallucinations & Retrieval Precision', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Parameter-Efficient Fine-Tuning (LoRA / QLoRA) Concepts', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-5',
        title: 'MLOps, Production Serving & Model Monitoring',
        description: 'FastAPI model endpoints, Docker containerization, MLflow experiment tracking, and cloud model monitoring.',
        skills: ['MLOps', 'FastAPI Serving', 'Docker for AI', 'MLflow', 'Model Monitoring'],
        estimatedWeeks: 4,
        whyItMatters: 'AI models generate zero value until reliably served at scale with latency SLAs in production.',
        conceptDetails: 'Batch vs real-time inference, model drift, data drift, GPU utilization, and CI/CD for machine learning.',
        practiceTask: 'Deploy an automated ML pipeline that accepts API requests, computes inference, and logs metrics.',
        quizId: 'mlops-serving',
        dailyTargets: [
          { day: 1, title: 'Wrapping PyTorch / Sklearn Models in FastAPI Endpoints', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Dockerizing the AI Service with CUDA Base Images', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Experiment Tracking & Model Registry with MLflow', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Batch Prediction Optimization & Async Queue Workers', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Monitoring Data & Concept Drift in Production', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'Deploying Inference Service to Cloud GPU Instances', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Stress-Testing API Latency & Generating Performance Report', duration: 60, difficulty: 'Medium' },
        ],
      },
    ],
  },
  'DevOps & Cloud Engineer': {
    title: 'DevOps & Cloud Engineer',
    defaultCountry: 'Germany',
    stages: [
      {
        id: 'stage-1',
        title: 'Linux Systems, Shell Scripting & Networking',
        description: 'Command line mastery, bash automation, process management, SSH security, DNS, and TCP/IP networking.',
        skills: ['Linux / Bash', 'Networking (DNS/TCP)', 'System Administration', 'SSH & Security'],
        estimatedWeeks: 4,
        whyItMatters: 'Enterprise cloud infrastructure runs on Linux kernels and networking protocols.',
        conceptDetails: 'File permissions, systemd services, cron jobs, network interfaces, firewalls (iptables/ufw), and packet routing.',
        practiceTask: 'Write a suite of automated bash scripts for server health monitoring and log rotation.',
        quizId: 'linux-networking',
        dailyTargets: [
          { day: 1, title: 'Linux Filesystem Hierarchy, Permissions & Ownership', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Bash Automation: Variables, Conditionals & Loops', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Process Management, Signals & systemd Service Configuration', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Networking Fundamentals: OSI Model, TCP/UDP & DNS Resolution', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'SSH Key Authentication, Port Forwarding & Security Hardening', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'Configuring UFW Firewalls & Reverse Proxy with Nginx', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Automated Server Provisioning Script Build', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-2',
        title: 'Containerization & Docker Orchestration',
        description: 'Docker architecture, Dockerfiles, multi-stage builds, networking, volumes, and Docker Compose environments.',
        skills: ['Docker', 'Multi-Stage Builds', 'Docker Compose', 'Container Security'],
        estimatedWeeks: 4,
        whyItMatters: 'Containers eliminate the "works on my machine" barrier across distributed development teams.',
        conceptDetails: 'Container layers, image optimization, volume persistence, bridge networks, and non-root security.',
        practiceTask: 'Containerize a 3-tier web application (frontend, backend, database) with healthchecks in Docker Compose.',
        quizId: 'docker-containers',
        dailyTargets: [
          { day: 1, title: 'Docker Core Architecture: Images, Containers & Daemon', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Writing Production Dockerfiles & Layer Caching', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Multi-Stage Builds for Minimalist Production Images', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Docker Volumes & Data Persistence Strategies', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Docker Networking: Bridge, Host & Custom Networks', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'Multi-Service Orchestration with Docker Compose', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Scanning Container Images for Vulnerabilities (Trivy)', duration: 60, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-3',
        title: 'Kubernetes Cluster Architecture & Management',
        description: 'Pods, Deployments, Services, Ingress, ConfigMaps, Secrets, and Helm package management.',
        skills: ['Kubernetes', 'Kubeconfig & Kubectl', 'Helm Charts', 'Ingress Controllers'],
        estimatedWeeks: 6,
        whyItMatters: 'Kubernetes is the international standard operating system for container orchestration at scale.',
        conceptDetails: 'Control plane vs worker nodes, rolling updates, self-healing, Horizontal Pod Autoscaling, and RBAC.',
        practiceTask: 'Deploy a resilient multi-replica service on a Kubernetes cluster with automated autoscaling.',
        quizId: 'kubernetes-orchestration',
        dailyTargets: [
          { day: 1, title: 'Kubernetes Architecture: Control Plane, Nodes & Kubelet', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Pods, ReplicaSets & Declarative YAML Deployments', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Kubernetes Services: ClusterIP, NodePort & LoadBalancer', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Managing Configuration: ConfigMaps & Encrypted Secrets', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Ingress Controllers & SSL Termination (Cert-Manager)', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Horizontal Pod Autoscaling (HPA) & Resource Limits', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Packaging Applications with Helm Charts', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-4',
        title: 'CI/CD Automation & Infrastructure as Code (Terraform)',
        description: 'GitHub Actions, GitLab CI, automated test runners, Terraform provisioning, and AWS cloud resources.',
        skills: ['CI/CD Pipelines', 'GitHub Actions', 'Terraform', 'AWS Cloud (VPC/EC2/S3)'],
        estimatedWeeks: 5,
        whyItMatters: 'Repeatable, code-defined infrastructure prevents configuration drift and enables instant cloud recreation.',
        conceptDetails: 'Terraform state management, plan/apply lifecycle, pipeline gates, secrets management, and cloud IAM.',
        practiceTask: 'Automate complete cloud infrastructure deployment using Terraform and GitHub Actions.',
        quizId: 'cicd-terraform',
        dailyTargets: [
          { day: 1, title: 'CI/CD Principles & Continuous Delivery Best Practices', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Configuring Multi-Stage GitHub Actions Pipelines', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Terraform Basics: Providers, Resources & Variables', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Managing Terraform State & Remote Backend (S3/DynamoDB)', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Provisioning AWS VPC, Subnets & Route Tables with Terraform', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Automated Pipeline Deploying Terraform Code with Checks', duration: 90, difficulty: 'Hard' },
          { day: 7, title: 'Cost Estimation & Infrastructure Teardown Verification', duration: 60, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-5',
        title: 'Observability, Logging & Site Reliability Engineering (SRE)',
        description: 'Prometheus metrics, Grafana dashboards, centralized logging (ELK/Loki), SLIs, SLOs, and incident response.',
        skills: ['Prometheus & Grafana', 'Log Aggregation', 'SLI/SLO Metrics', 'Incident Response'],
        estimatedWeeks: 4,
        whyItMatters: 'High-availability services require real-time visibility into errors, saturation, and latency spikes.',
        conceptDetails: 'The Four Golden Signals, alerting rules, distributed tracing, post-mortem methodology, and chaos engineering.',
        practiceTask: 'Set up a full observability stack that fires automated Discord/Slack alerts during service degradation.',
        quizId: 'observability-sre',
        dailyTargets: [
          { day: 1, title: 'SRE Core Concepts: SLAs, SLOs & Error Budgets', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Exporting Metrics & Setting Up Prometheus Server', duration: 90, difficulty: 'Medium' },
          { day: 3, title: 'Building Real-Time Performance Dashboards in Grafana', duration: 90, difficulty: 'Medium' },
          { day: 4, title: 'Centralized Logging Architecture with Loki / Vector', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Configuring Alertmanager Rules & Notification Webhooks', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'Simulating Outages & Writing SRE Incident Post-Mortems', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Complete Cloud Infrastructure Capstone Review', duration: 90, difficulty: 'Hard' },
        ],
      },
    ],
  },
  'Cybersecurity Analyst': {
    title: 'Cybersecurity Analyst',
    defaultCountry: 'USA',
    stages: [
      {
        id: 'stage-1',
        title: 'Security Foundations, Protocols & System Defense',
        description: 'Security principles (CIA triad), defense-in-depth, network protocols, cryptography, and vulnerability scanning.',
        skills: ['Network Security', 'Cryptography', 'Linux & Windows Security', 'Wireshark'],
        estimatedWeeks: 4,
        whyItMatters: 'Every defensive security analyst must understand packet structures and cryptographic handshakes.',
        conceptDetails: 'Symmetric/asymmetric encryption, PKI certificates, packet sniffing, port scanning (Nmap), and firewall rules.',
        practiceTask: 'Capture and dissect network traffic to identify unencrypted credentials and malicious handshakes.',
        quizId: 'security-foundations',
        dailyTargets: [
          { day: 1, title: 'The CIA Triad & Threat Modeling Frameworks (STRIDE)', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'TCP/IP Packet Structure & Deep Inspection with Wireshark', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Cryptography: AES, RSA, Hashing & Digital Signatures', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Port Scanning, Banner Grabbing & Reconnaissance with Nmap', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Host-Based Security & Audit Policies in Linux and Windows', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Vulnerability Assessment with Nessus / OpenVAS', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Network Security Audit Report Compilation', duration: 60, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-2',
        title: 'Threat Detection, SIEM & Security Operations Center (SOC)',
        description: 'Log analysis, SIEM tools (Splunk/Elastic), detection engineering, alert triage, and MITRE ATT&CK mapping.',
        skills: ['SIEM (Splunk / Elastic)', 'Log Analysis', 'Detection Rules', 'MITRE ATT&CK'],
        estimatedWeeks: 5,
        whyItMatters: 'SOC teams protect enterprises by detecting intrusions within minutes through automated correlation.',
        conceptDetails: 'Syslog formats, correlation rules, indicators of compromise (IOCs), threat feeds, and triage prioritization.',
        practiceTask: 'Configure SIEM correlation rules to trigger alerts upon brute-force SSH attempts and privilege escalation.',
        quizId: 'soc-threat-detection',
        dailyTargets: [
          { day: 1, title: 'SOC Operations: Roles, Workflows & Incident Lifecycles', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Ingesting & Normalizing System Logs in SIEM', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Writing Search Queries in Splunk / Elastic (KQL/SPL)', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Mapping Adversary Techniques to MITRE ATT&CK Framework', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Developing Detection Rules for Persistence & Lateral Movement', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Investigating Phishing Emails & Malicious Headers', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Simulated Security Incident Triage Exercise', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-3',
        title: 'Web Application Security & OWASP Top 10',
        description: 'SQL injection, Cross-Site Scripting (XSS), CSRF, authentication bypass, and Burp Suite interception.',
        skills: ['OWASP Top 10', 'Burp Suite', 'Web Vulnerability Exploitation', 'Remediation'],
        estimatedWeeks: 5,
        whyItMatters: 'Web apps are the primary attack surface targeting consumer data and enterprise credentials.',
        conceptDetails: 'HTTP proxying, reflected vs stored XSS, parameterized queries, authorization flaws, and secure headers.',
        practiceTask: 'Audit a vulnerable web application using Burp Suite and document detailed remediation patches.',
        quizId: 'web-security-owasp',
        dailyTargets: [
          { day: 1, title: 'OWASP Top 10 Deep Dive & Application Threat Vectors', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Burp Suite Setup, Request Interception & Repeater Tool', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'SQL Injection: Blind, Error-Based & Union Exploits', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Cross-Site Scripting (XSS) & Content Security Policy (CSP)', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Broken Object Level Authorization (BOLA) & Access Control Flaws', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Security Code Review & Secure Coding Best Practices', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Web Application Penetration Test Report Build', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-4',
        title: 'Incident Response, Forensics & Cloud Security',
        description: 'Memory analysis, disk forensics, malware triage, incident containment, and AWS IAM cloud security policies.',
        skills: ['Incident Response', 'Digital Forensics', 'Cloud Security (AWS)', 'Compliance (ISO 27001)'],
        estimatedWeeks: 4,
        whyItMatters: 'Organizations require certified response capabilities to isolate breaches and satisfy regulatory audits.',
        conceptDetails: 'Chain of custody, Volatility memory analysis, cloud audit trails (CloudTrail), and ransomware playbooks.',
        practiceTask: 'Execute a memory dump analysis to recover an injected malicious process payload.',
        quizId: 'incident-response-forensics',
        dailyTargets: [
          { day: 1, title: 'Incident Response Frameworks: NIST & SANS Methodologies', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Memory Forensics with Volatility: Detecting Injected DLLs', duration: 90, difficulty: 'Hard' },
          { day: 3, title: 'Disk Image Extraction & Timeline Analysis with Autopsy', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'AWS Cloud Security: IAM Policies, GuardDuty & CloudTrail Auditing', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Drafting Playbooks for Ransomware & Data Exfiltration Containment', duration: 60, difficulty: 'Medium' },
          { day: 6, title: 'Regulatory Compliance Standards: GDPR, ISO 27001 & SOC 2', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Final Incident Response Simulation & Industry Presentation', duration: 90, difficulty: 'Hard' },
        ],
      },
    ],
  },
};

/**
 * Helper to dynamically create a software curriculum for any custom role entered by user
 */
function createCustomSoftwareProfile(roleTitle = 'Software Specialist', country = 'Germany') {
  return {
    title: roleTitle,
    defaultCountry: country,
    stages: [
      {
        id: 'stage-1',
        title: `${roleTitle} Fundamentals & Core Tools`,
        description: `Foundational syntax, software development tools, version control, and core principles of ${roleTitle}.`,
        skills: ['Core Programming', 'Git & GitHub', 'Computer Science Fundamentals', 'Problem Solving'],
        estimatedWeeks: 4,
        whyItMatters: `Solid fundamentals ensure mastery of advanced concepts and rapid troubleshooting in ${roleTitle}.`,
        conceptDetails: 'Syntax constructs, algorithmic thinking, development environments, and version control workflows.',
        practiceTask: `Complete 5 structured coding challenges and publish the source repository on GitHub.`,
        quizId: 'fundamentals-tech',
        dailyTargets: [
          { day: 1, title: 'Environment Setup & Modern Development Workflow', duration: 45, difficulty: 'Easy' },
          { day: 2, title: 'Core Syntax, Data Types & Variables', duration: 60, difficulty: 'Easy' },
          { day: 3, title: 'Control Flow, Functions & Modular Code', duration: 60, difficulty: 'Medium' },
          { day: 4, title: 'Data Structures & Memory Basics', duration: 90, difficulty: 'Medium' },
          { day: 5, title: 'Version Control with Git & Branching Strategy', duration: 45, difficulty: 'Easy' },
          { day: 6, title: 'Debugging Techniques & Error Handling', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Foundational Mini-Project Build', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-2',
        title: `Architecture, Data & Systems Engineering`,
        description: `Designing scalable services, relational data models, API contracts, and component architecture for ${roleTitle}.`,
        skills: ['System Design', 'Databases & SQL', 'API Architecture', 'Component Design'],
        estimatedWeeks: 5,
        whyItMatters: `Production software requires clean modular separation, data integrity, and performant query execution.`,
        conceptDetails: 'Database normalization, indexing, RESTful standards, authentication, and state management.',
        practiceTask: `Architect and build a backend database service with automated input validation.`,
        quizId: 'architecture-data',
        dailyTargets: [
          { day: 1, title: 'System Architecture & Component Decomposition', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Database Schema Design & Normalization', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Writing Optimized SQL Queries & Indices', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Designing RESTful Endpoints & Validation', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Authentication, Authorization & Session Security', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Integration Testing & API Contract Verification', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Service Integration Milestone Review', duration: 90, difficulty: 'Hard' },
        ],
      },
      {
        id: 'stage-3',
        title: `Cloud Deployment, DevOps & Containerization`,
        description: `Automating test suites, Docker containers, CI/CD pipelines, and cloud platform deployment.`,
        skills: ['Docker', 'CI/CD Pipelines', 'Cloud Hosting', 'Infrastructure Monitoring'],
        estimatedWeeks: 4,
        whyItMatters: `Modern engineering requires building code that can be automatically built, tested, and deployed to cloud environments.`,
        conceptDetails: 'Dockerfiles, multi-stage builds, GitHub Actions workflows, cloud environment variables, and telemetry.',
        practiceTask: `Deploy your application to a live cloud host with automated continuous integration.`,
        quizId: 'cloud-devops',
        dailyTargets: [
          { day: 1, title: 'Containerizing Applications with Docker', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Docker Compose for Multi-Service Environments', duration: 60, difficulty: 'Medium' },
          { day: 3, title: 'Continuous Integration Workflows with GitHub Actions', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Deploying Services to Production Cloud Platforms', duration: 90, difficulty: 'Hard' },
          { day: 5, title: 'Configuring Domain Names & SSL Encryption', duration: 45, difficulty: 'Easy' },
          { day: 6, title: 'Setting Up Health Monitoring & Error Logging', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Cloud Verification & Reliability Audit', duration: 60, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-4',
        title: `Capstone Production Project & Portfolio`,
        description: `End-to-end production-grade software project solving a real-world problem with live users.`,
        skills: ['Full Project Lifecycle', 'Production Testing', 'Clean Code', 'Portfolio Documentation'],
        estimatedWeeks: 4,
        whyItMatters: `A deployed, demonstrable project proves hands-on competence to recruiters and hiring managers.`,
        conceptDetails: 'Comprehensive testing, security hardening, user documentation, and video demonstration.',
        practiceTask: `Ship your capstone project live with public GitHub source and demo video.`,
        quizId: 'capstone-engineering',
        dailyTargets: [
          { day: 1, title: 'Capstone Scope Definition & Architecture Blueprint', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Core Functionality Build & Business Logic', duration: 120, difficulty: 'Hard' },
          { day: 3, title: 'User Interface Refinement & Responsive Polish', duration: 90, difficulty: 'Medium' },
          { day: 4, title: 'Security Audit & Rate Limiting Implementation', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Automated Test Suites & Edge Case Coverage', duration: 90, difficulty: 'Hard' },
          { day: 6, title: 'Production Cloud Deployment & Performance Tuning', duration: 60, difficulty: 'Medium' },
          { day: 7, title: 'Publishing Case Study, GitHub README & Demo Video', duration: 90, difficulty: 'Medium' },
        ],
      },
      {
        id: 'stage-5',
        title: `Career Readiness & Interview Preparation (${country} Pathway)`,
        description: `Technical interview preparation, resume optimization, portfolio showcase, and hiring pathway requirements.`,
        skills: ['Technical Interviews', 'ATS Resume', 'System Design', 'Pathway Hiring Requirements'],
        estimatedWeeks: 3,
        whyItMatters: `Translating technical skills into high-paying employment requires targeted interview strategy and country positioning.`,
        conceptDetails: 'Mock interview rounds, STAR behavioral questions, recruiter networking, and visa criteria.',
        practiceTask: `Complete 3 timed technical interviews and submit 10 personalized job applications.`,
        quizId: 'career-readiness',
        dailyTargets: [
          { day: 1, title: 'Engineering Resume Optimization for ATS Screening', duration: 60, difficulty: 'Medium' },
          { day: 2, title: 'Optimizing LinkedIn & GitHub for International Recruiters', duration: 45, difficulty: 'Easy' },
          { day: 3, title: 'System Design & Architecture Interview Practice', duration: 90, difficulty: 'Hard' },
          { day: 4, title: 'Behavioral Questions & STAR Method Responses', duration: 60, difficulty: 'Medium' },
          { day: 5, title: 'Live Coding Interview Simulation', duration: 90, difficulty: 'Hard' },
          { day: 6, title: `Researching ${country} Visa & Market Requirements`, duration: 45, difficulty: 'Easy' },
          { day: 7, title: 'Submitting Applications & Tracking Opportunities', duration: 60, difficulty: 'Medium' },
        ],
      },
    ],
  };
}

/**
 * Generate a complete FutureForge Roadmap tailored to user goal & country
 * @param {string} jobRole
 * @param {string} country
 * @returns {object} Roadmap structure with stages, targets, milestones
 */
export function generatePersonalizedRoadmap(jobRole = 'Software Engineer', country = 'Germany') {
  // Use matched profile or generate a high-quality tailored software curriculum
  const baseProfile = CAREER_PROFILES[jobRole] || createCustomSoftwareProfile(jobRole, country || 'Germany');
  const targetCountry = country || baseProfile.defaultCountry || 'Germany';

  const stages = baseProfile.stages.map((stage, index) => ({
    ...stage,
    status: index === 0 ? 'active' : 'locked',
    progress: index === 0 ? 0 : 0,
    order: index + 1,
  }));

  // Build Weekly, Monthly, Yearly target breakdowns
  const weeklyTargets = stages.flatMap((stage, sIdx) => 
    Array.from({ length: stage.estimatedWeeks }, (_, wIdx) => ({
      id: `w-${sIdx + 1}-${wIdx + 1}`,
      stageId: stage.id,
      weekNumber: sIdx * 4 + wIdx + 1,
      title: `${stage.title} — Part ${wIdx + 1}`,
      description: `Complete weekly learning milestones and practice exercises for ${stage.title}.`,
      skills: stage.skills,
      status: sIdx === 0 && wIdx === 0 ? 'in_progress' : 'locked',
      totalDays: 7,
      completedDays: 0,
    }))
  );

  const monthlyTargets = stages.map((stage, idx) => ({
    id: `m-${idx + 1}`,
    monthNumber: idx + 1,
    title: `Month ${idx + 1}: ${stage.title}`,
    milestone: `Master ${stage.title} and pass the Skill Quiz benchmark.`,
    expectedOutcome: stage.practiceTask,
    status: idx === 0 ? 'in_progress' : 'locked',
    progress: 0,
  }));

  const yearlyTargets = [
    {
      id: 'y-1',
      year: 1,
      title: `Career-Ready ${jobRole} (${targetCountry} Pathway)`,
      goal: `Build foundational to advanced ${jobRole} skills, pass skill quizzes, complete production capstone, and prepare international career applications for ${targetCountry}.`,
      milestones: stages.map(s => s.title),
      status: 'in_progress',
      progress: 0,
    },
  ];

  return {
    goal: jobRole,
    country: targetCountry,
    totalSteps: stages.length,
    completedSteps: 0,
    currentStepIndex: 0,
    steps: stages,
    weeklyTargets,
    monthlyTargets,
    yearlyTargets,
  };
}
